import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { User } from "lucide-react";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

import {
  QueryClient,
  QueryClientProvider,
  useQuery,
} from "@tanstack/react-query";
import { ReactQueryClientProvider } from "@/components/ReactQueryClientProvider";
import { ToastContainer, toast } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ACT Local",
  description: "Generated by create next app",
};

const apiKey = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY;
const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <ReactQueryClientProvider>
        <html lang="en">
          <head>
            <link
              href="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.css"
              rel="stylesheet"
            />
          </head>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <nav className="bg-blue-600 text-white w-full p-4">
              <div className="flex justify-between items-center">
                <div className="text-2xl font-bold">
                  <Link href="/tasks">ACT Local</Link>
                </div>
                <div className="space-x-6 hidden md:flex">
                  <a href="/tasks" className="hover:text-gray-200">
                    Home
                  </a>
                  <a href="#about" className="hover:text-gray-200">
                    About
                  </a>
                  <a href="#contact" className="hover:text-gray-200">
                    Contact
                  </a>
                  <SignedIn>
                    <a href="/tasks/me" className="hover:text-gray-200">
                      My Tasks
                    </a>
                  </SignedIn>
                </div>
                {/* Profile Icon */}
                <div className="relative">
                  <SignedOut>
                    <SignInButton />
                  </SignedOut>
                  <SignedIn>
                    <UserButton />
                  </SignedIn>
                </div>
              </div>
            </nav>
            {children}
            <ToastContainer />
            <script src="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.js"></script>
            <script
              src={`https://maps.googleapis.com/maps/api/js?key=${apiKey}&libraries=places`}
            ></script>
          </body>
        </html>
      </ReactQueryClientProvider>
    </ClerkProvider>
  );
}
