import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { User } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ACT Local",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.css"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-blue-600 text-white w-full p-4">
          <div className="flex justify-between items-center">
            <div className="text-2xl font-bold"><Link href="/">ACT Local</Link></div>
            <div className="space-x-6 hidden md:flex">
              <a href="/" className="hover:text-gray-200">
                Home
              </a>
              <a href="#opportunities" className="hover:text-gray-200">
                Opportunities
              </a>
              <a href="#about" className="hover:text-gray-200">
                About
              </a>
              <a href="#contact" className="hover:text-gray-200">
                Contact
              </a>
            </div>
            {/* Profile Icon */}
            <div className="relative">
              {/* <Link href={"/tasks/me"}>
                <User className="w-6 h-6 text-white cursor-pointer" />
              </Link> */}
              <Link href="/auth">Sign In / Register</Link>
            </div>
          </div>
        </nav>
        {children}
        <script src="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.js"></script>
      </body>
    </html>
  );
}
